from typing import Union
from .tasks import *

ModelActionConfig = Union[
    TextGenerationModelActionConfig,
    ChatCompletionModelActionConfig,
    TextToTextModelActionConfig,
    TextClassificationModelActionConfig,
    TextEmbeddingModelActionConfig,
    TextRerankingModelActionConfig,
    TypedDecisionModelActionConfig,
    ImageToTextModelActionConfig,
    ImageTextToTextModelActionConfig,
    ImageGenerationModelActionConfig,
    ImageEmbeddingModelActionConfig,
    VideoEmbeddingModelActionConfig,
    ImageUpscalingModelActionConfig,
    ImageBackgroundRemovalModelActionConfig,
    ImageSegmentationModelActionConfig,
    TextToVideoModelActionConfig,
    ImageToVideoModelActionConfig,
    VideoToVideoModelActionConfig,
    ImageTo3DModelActionConfig,
    TalkingHeadModelActionConfig,
    LipSyncModelActionConfig,
    ObjectDetectionModelActionConfig,
    ObjectTrackingModelActionConfig,
    ShotBoundaryDetectionModelActionConfig,
    FaceDetectionModelActionConfig,
    PoseDetectionModelActionConfig,
    PoseTrackingModelActionConfig,
    FaceEmbeddingModelActionConfig,
    FaceTrackingModelActionConfig,
    FaceSwapModelActionConfig,
    TextToSpeechModelActionConfig,
    SpeechToTextModelActionConfig,
    AudioTextAlignmentModelActionConfig,
    VoiceActivityDetectionModelActionConfig,
    SpeakerDiarizationModelActionConfig,
    MusicGenerationModelActionConfig,
    MotionGenerationModelActionConfig,
    MusicSourceSeparationModelActionConfig,
    MusicTranscriptionModelActionConfig,
    MusicBeatTrackingModelActionConfig,
    MusicEmbeddingModelActionConfig,
    VoiceEmbeddingModelActionConfig,
]
