from typing import Type, Union, Literal, Optional, Dict, List, Tuple, Set, Annotated, Any
from pydantic import BaseModel, Field
from .impl import *

ComponentConfig = Annotated[
    Union[
        HttpServerComponentConfig,
        HttpClientComponentConfig,
        WebSocketServerComponentConfig,
        WebSocketClientComponentConfig,
        McpServerComponentConfig,
        McpClientComponentConfig,
        ModelComponentConfig,
        ModelMemoryComponentConfig,
        ModelTokenizerComponentConfig,
        DatasetsComponentConfig,
        VectorStoreComponentConfig,
        WorkflowComponentConfig,
        ShellComponentConfig,
        TextSplitterComponentConfig,
        SentenceSplitterComponentConfig,
        TranscriptCorrectorComponentConfig,
        ImageProcessorComponentConfig,
        VectorProcessorComponentConfig,
        WebScraperComponentConfig,
        AgentComponentConfig,
        WebBrowserComponentConfig,
        HtmlFrameRendererComponentConfig,
        VideoSceneDetectorComponentConfig,
        VideoClipperComponentConfig,
        VideoConverterComponentConfig,
        VideoEncoderComponentConfig,
        VideoFrameExtractorComponentConfig,
        VideoMixerComponentConfig,
        ScreenCaptureComponentConfig,
        RtmpPublisherComponentConfig,
        MediaInspectorComponentConfig,
        MediaDownloaderComponentConfig,
        AudioExtractorComponentConfig,
        AudioClipperComponentConfig,
        AudioConverterComponentConfig,
        AudioProcessorComponentConfig,
        AudioFeatureExtractorComponentConfig,
        AudioPlaybackComponentConfig,
        AudioMixerComponentConfig,
        KeyValueStoreComponentConfig,
        GraphStoreComponentConfig,
        FileStoreComponentConfig,
        SearchEngineComponentConfig,
        DataQueueComponentConfig
    ],
    Field(discriminator="type")
]
