controller:
  type: http-server
  port: 8080
  base_path: /api
  webui:
    port: 8081

gateway:
  type: ssh-tunnel
  port:
    - "9834:8090"  # Forward from remote port 9834 to local port 8090
  connection:
    host: ${env.SSH_TUNNEL_HOST}
    port: ${env.SSH_TUNNEL_PORT | 22}
    auth:
      type: ${env.SSH_AUTH_TYPE | keyfile}
      username: ${env.SSH_USERNAME}
      keyfile: ${env.SSH_KEYFILE | ~/.ssh/id_rsa}

listener:
  type: http-callback
  host: 0.0.0.0
  port: 8090
  path: /callback
  identify_by: ${body.task_id}
  result: ${body.result}

component:
  type: http-server
  start: [ uvicorn, server:app, --reload, --port, "9000" ]
  port: 9000
  method: POST
  path: /process
  headers:
    Content-Type: application/json
  body:
    data: ${input.data}
    # Use gateway's public address for callback
    callback_url: http://${gateway:8090.public_address}/callback
    task_id: ${context.run_id}
  completion:
    type: callback
    wait_for: ${context.run_id}
  output:
    task_id: ${response.task_id}
    result: ${result as json}

workflow:
  title: SSH Tunnel Gateway Example
  description: Demonstrates using SSH tunnel to expose local callback listener to external services
  input: ${input}
  output: ${output}
