controller:
  type: http-server
  port: 8080
  base_path: /api
  webui:
    driver: gradio
    port: 8081

workflow:
  title: Text to Speech with Qwen3-TTS
  description: Generate speech audio from text using Qwen3-TTS via vLLM-Omni
  input: ${input}
  output: ${output as audio}

component:
  type: http-server
  manage:
    install:
      - bash
      - -c
      - |
        eval "$(pyenv init -)" &&
        (pyenv activate vllm-omni 2>/dev/null || pyenv virtualenv $(python --version | cut -d' ' -f2) vllm-omni) &&
        pyenv activate vllm-omni &&
        pip install vllm &&
        pip install vllm-omni
    start:
      - bash
      - -c
      - |
        eval "$(pyenv init -)" &&
        pyenv activate vllm-omni &&
        vllm serve Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice \
          --stage-configs-path vllm_omni/model_executor/stage_configs/qwen3_tts.yaml \
          --omni \
          --port 8091 \
          --trust-remote-code \
          --enforce-eager
  port: 8091
  method: POST
  path: /v1/audio/speech
  headers:
    Content-Type: application/json
  body:
    input: ${input.text as text}
    voice: ${input.voice | vivian}
    language: ${input.language | Auto}
    instructions: ${input.instructions | ""}
    response_format: wav
  output: ${response}
