controller:
  type: http-server
  port: 8080
  base_path: /api
  webui:
    driver: gradio
    port: 8081

workflow:
  title: Generate Transcriptions with OpenAI STT
  description: Convert audio files to text using OpenAI's Whisper and transcription models. 
  jobs:
    - id: speech-to-text
      component: openai-speech-to-text
      input: ${input}
      output: 
        text: ${output.text}
        seconds: ${output.usage.seconds}

components:
  - id: openai-speech-to-text
    type: http-client
    action:
      endpoint: https://api.openai.com/v1/audio/transcriptions
      method: POST
      headers:
        Authorization: Bearer ${env.OPENAI_API_KEY}
        Content-Type:  multipart/form-data
      body:
        model: ${input.model as select/gpt-4o-transcribe,gpt-4o-mini-transcribe,whisper-1 | whisper-1}
        file: ${input.file as audio}
      output: ${response}
