controller:
  adapter:
    type: http-server
    port: 8080
    base_path: /api
  webui:
    driver: gradio
    port: 8081

workflow:
  title: Translate Text (Streaming)
  description: Translate the input text into another language using a pretrained seq2seq translation model, streaming tokens as they are produced.
  job:
    input: ${input}
    output: ${output as stream/text}

component:
  type: model
  task: text-to-text
  driver: huggingface
  model: alirezamsh/small100
  max_concurrent_count: 1
  action:
    text: ${input.text as text}
    max_input_length: 1024
    streaming: true
    params:
      do_sample: false
