controller:
  type: http-server
  port: 8080
  base_path: /api
  webui:
    port: 8081

gateway:
  type: http-tunnel
  driver: ngrok
  port:
    - 8090  # Expose local port 8090 via ngrok tunnel

listener:
  type: http-callback
  host: 0.0.0.0
  port: 8090
  path: /callback
  identify_by: ${body.task_id}
  result: ${body.result}

workflow:
  title: Ngrok HTTP Tunnel Gateway Example
  description: Demonstrates using ngrok to expose local callback listener to external services
  input: ${input}
  output: ${output}

component:
  type: http-server
  start: [ uvicorn, server:app, --reload, --port, "9000" ]
  port: 9000
  action:
    method: POST
    path: /process
    headers:
      Content-Type: application/json
    body:
      data: ${input.data}
      # Use gateway's public url for callback
      callback_url: ${gateway:8090.public_url}/callback
      task_id: ${context.run_id}
    completion:
      type: callback
      wait_for: ${context.run_id}
    output:
      task_id: ${response.task_id}
      result: ${result as json}
