controller:
  type: http-server
  port: 8080
  base_path: /api
  webui:
    driver: gradio
    port: 8081

workflow:
  title: Generate Text from Prompt
  description: Generate text based on a given prompt using a pretrained language model.
  input: ${input}
  output:
    generated: ${output}

component:
  type: model
  task: text-generation
  model: HuggingFaceTB/SmolLM3-3B
  max_concurrent_count: 1
  action:
    text: ${input.prompt as text}
    params:
      max_output_length: 32768
