from typing import Union, Annotated
from pydantic import Field
from .common import (
    AudioProcessorResampleActionConfig,
    AudioProcessorHighpassActionConfig,
    AudioProcessorLowpassActionConfig,
    AudioProcessorBellActionConfig,
    AudioProcessorLowShelfActionConfig,
    AudioProcessorHighShelfActionConfig,
    AudioProcessorPitchShiftActionConfig,
    AudioProcessorDcShiftActionConfig,
    AudioProcessorCompressorActionConfig,
    AudioProcessorNoiseGateActionConfig,
    AudioProcessorDistortionActionConfig,
    AudioProcessorSaturationActionConfig,
    AudioProcessorGainActionConfig,
    AudioProcessorChorusActionConfig,
    AudioProcessorDelayActionConfig,
    AudioProcessorReverbActionConfig,
    AudioProcessorNormalizeActionConfig,
    AudioProcessorPeakLimitActionConfig,
    AudioProcessorTrimEdgesActionConfig,
    AudioProcessorTrimSilenceActionConfig,
    AudioProcessorFadeInActionConfig,
    AudioProcessorFadeOutActionConfig,
    AudioProcessorAnonymizeActionConfig,
)

NativeAudioProcessorActionConfig = Annotated[
    Union[
        AudioProcessorResampleActionConfig,
        AudioProcessorHighpassActionConfig,
        AudioProcessorLowpassActionConfig,
        AudioProcessorBellActionConfig,
        AudioProcessorLowShelfActionConfig,
        AudioProcessorHighShelfActionConfig,
        AudioProcessorPitchShiftActionConfig,
        AudioProcessorDcShiftActionConfig,
        AudioProcessorCompressorActionConfig,
        AudioProcessorNoiseGateActionConfig,
        AudioProcessorDistortionActionConfig,
        AudioProcessorSaturationActionConfig,
        AudioProcessorGainActionConfig,
        AudioProcessorChorusActionConfig,
        AudioProcessorDelayActionConfig,
        AudioProcessorReverbActionConfig,
        AudioProcessorNormalizeActionConfig,
        AudioProcessorPeakLimitActionConfig,
        AudioProcessorTrimEdgesActionConfig,
        AudioProcessorTrimSilenceActionConfig,
        AudioProcessorFadeInActionConfig,
        AudioProcessorFadeOutActionConfig,
    ],
    Field(discriminator="method")
]
