controller:
  type: http-server
  port: 8080
  base_path: /api
  webui:
    driver: gradio
    port: 8081

component: 
  type: http-client
  base_url: https://api.openai.com/v1
  path: /chat/completions
  method: POST
  headers:
    Authorization: Bearer ${env.OPENAI_API_KEY}
    Content-Type: application/json
  body:
    model: gpt-4o
    messages:
      - role: user
        content: ${input.prompt}
    temperature: ${input.temperature as number | 0.7}
  output:
    message: ${response.choices[0].message.content}

workflow:
  title: OpenAI GPT-4o Chatbot
  description: Generate natural language responses from OpenAI's GPT-4o model using a prompt and optional temperature setting.
  input: ${input}
  output: ${output}
