from typing import Type, Union, Literal, Optional, Dict, List, Tuple, Set, Annotated, Any
from pydantic import BaseModel, Field
from .impl import *

ActionConfig = Union[
    HttpServerActionConfig,
    HttpClientActionConfig,
    WebSocketServerActionConfig,
    WebSocketClientActionConfig,
    McpServerActionConfig,
    McpClientActionConfig,
    ModelActionConfig,
    ModelMemoryActionConfig,
    ModelTokenizerActionConfig,
    WorkflowActionConfig,
    ShellActionConfig,
    TextSplitterActionConfig,
    SentenceSplitterActionConfig,
    TranscriptCorrectorActionConfig,
    ImageProcessorActionConfig,
    VectorProcessorActionConfig,
    AgentActionConfig,
    WebBrowserActionConfig,
    HtmlFrameRendererActionConfig,
    VideoSceneDetectorActionConfig,
    VideoClipperActionConfig,
    VideoConverterActionConfig,
    VideoEncoderActionConfig,
    VideoFrameExtractorActionConfig,
    VideoMixerActionConfig,
    ScreenCaptureActionConfig,
    RtmpPublisherActionConfig,
    MediaInspectorActionConfig,
    AudioExtractorActionConfig,
    AudioClipperActionConfig,
    AudioProcessorActionConfig,
    AudioPlaybackActionConfig,
    AudioMixerActionConfig,
    KeyValueStoreActionConfig,
    GraphStoreActionConfig,
    FileStoreActionConfig,
    SearchEngineActionConfig,
    DataQueueActionConfig
]
