from typing import Dict, List
from mindor.dsl.schema.action import TextSplitterLanguage

_FALLBACK: List[str] = [ "\n\n", "\n", " ", "" ]

LANGUAGE_SEPARATORS: Dict[TextSplitterLanguage, List[str]] = {
    TextSplitterLanguage.PYTHON: [
        "\nclass ",
        "\ndef ",
        "\n\tdef ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.JAVASCRIPT: [
        "\nfunction ",
        "\nconst ",
        "\nlet ",
        "\nvar ",
        "\nclass ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nswitch ",
        "\ncase ",
        "\ndefault ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.TYPESCRIPT: [
        "\nfunction ",
        "\nconst ",
        "\nlet ",
        "\nvar ",
        "\nclass ",
        "\ninterface ",
        "\ntype ",
        "\nenum ",
        "\nnamespace ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nswitch ",
        "\ncase ",
        "\ndefault ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.JAVA: [
        "\nclass ",
        "\npublic ",
        "\nprotected ",
        "\nprivate ",
        "\nstatic ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nswitch ",
        "\ncase ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.KOTLIN: [
        "\nclass ",
        "\nobject ",
        "\ninterface ",
        "\nfun ",
        "\nval ",
        "\nvar ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nwhen ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.SCALA: [
        "\nclass ",
        "\nobject ",
        "\ntrait ",
        "\ndef ",
        "\nval ",
        "\nvar ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nmatch ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.GO: [
        "\nfunc ",
        "\nvar ",
        "\nconst ",
        "\ntype ",
        "\nif ",
        "\nfor ",
        "\nswitch ",
        "\ncase ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.RUST: [
        "\nfn ",
        "\nconst ",
        "\nlet ",
        "\nstatic ",
        "\nstruct ",
        "\nenum ",
        "\ntrait ",
        "\nimpl ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nloop ",
        "\nmatch ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.CPP: [
        "\nclass ",
        "\nvoid ",
        "\nint ",
        "\nfloat ",
        "\ndouble ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nswitch ",
        "\ncase ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.C: [
        "\nvoid ",
        "\nint ",
        "\nfloat ",
        "\ndouble ",
        "\nchar ",
        "\nstruct ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nswitch ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.CSHARP: [
        "\nclass ",
        "\npublic ",
        "\nprivate ",
        "\nprotected ",
        "\ninternal ",
        "\nstatic ",
        "\nnamespace ",
        "\nif ",
        "\nfor ",
        "\nforeach ",
        "\nwhile ",
        "\nswitch ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.RUBY: [
        "\ndef ",
        "\nclass ",
        "\nmodule ",
        "\nif ",
        "\nunless ",
        "\nwhile ",
        "\nfor ",
        "\ndo ",
        "\nbegin ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.PHP: [
        "\nfunction ",
        "\nclass ",
        "\nif ",
        "\nforeach ",
        "\nwhile ",
        "\nfor ",
        "\nswitch ",
        "\ncase ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.SWIFT: [
        "\nfunc ",
        "\nclass ",
        "\nstruct ",
        "\nenum ",
        "\nprotocol ",
        "\nextension ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nswitch ",
        "\ncase ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.HTML: [
        "<body",
        "<div",
        "<p",
        "<br",
        "<li",
        "<h1",
        "<h2",
        "<h3",
        "<h4",
        "<h5",
        "<h6",
        "<span",
        "<table",
        "<tr",
        "<td",
        "<th",
        "<ul",
        "<ol",
        "<header",
        "<footer",
        "<nav",
        "<head",
        "<style",
        "<script",
        "<meta",
        "<title",
        "",
    ],
    TextSplitterLanguage.MARKDOWN: [
        "\n## ",
        "\n### ",
        "\n#### ",
        "\n##### ",
        "\n###### ",
        "```\n",
        "\n\n---\n",
        "\n\n***\n",
        "\n\n___\n",
        *_FALLBACK,
    ],
    TextSplitterLanguage.LATEX: [
        "\n\\chapter{",
        "\n\\section{",
        "\n\\subsection{",
        "\n\\subsubsection{",
        "\n\\begin{enumerate}",
        "\n\\begin{itemize}",
        "\n\\begin{description}",
        "\n\\begin{list}",
        "\n\\begin{quote}",
        "\n\\begin{quotation}",
        "\n\\begin{verse}",
        "\n\\begin{verbatim}",
        "\n\\begin{align}",
        "$$",
        "$",
        *_FALLBACK,
    ],
    TextSplitterLanguage.SQL: [
        "\nSELECT ",
        "\nFROM ",
        "\nWHERE ",
        "\nGROUP BY ",
        "\nORDER BY ",
        "\nHAVING ",
        "\nJOIN ",
        "\nLEFT JOIN ",
        "\nRIGHT JOIN ",
        "\nINNER JOIN ",
        "\nOUTER JOIN ",
        "\nUNION ",
        "\nINSERT ",
        "\nUPDATE ",
        "\nDELETE ",
        "\nCREATE ",
        "\nDROP ",
        "\nALTER ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.SOLIDITY: [
        "\npragma ",
        "\nusing ",
        "\ncontract ",
        "\ninterface ",
        "\nlibrary ",
        "\nconstructor ",
        "\ntype ",
        "\nfunction ",
        "\nevent ",
        "\nmodifier ",
        "\nerror ",
        "\nstruct ",
        "\nenum ",
        "\nmapping ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\ndo ",
        "\nassembly ",
        *_FALLBACK,
    ],
    TextSplitterLanguage.PROTO: [
        "\nmessage ",
        "\nservice ",
        "\nenum ",
        "\noptions ",
        "\nimport ",
        "\nsyntax ",
        *_FALLBACK,
    ],
}

DEFAULT_SEPARATORS: List[str] = list(_FALLBACK)

def from_language(language: TextSplitterLanguage) -> List[str]:
    """Return the separator list for ``language``.

    Mirrors LangChain's ``RecursiveCharacterTextSplitter.from_language``
    naming. Enum coverage is enforced at the schema layer; a missing entry
    here means a new enum value was added without a corresponding preset.
    """
    separators = LANGUAGE_SEPARATORS.get(language)

    if separators is None:
        raise ValueError(f"No separators defined for language: {language.value}")

    return list(separators)
