controller:
  type: http-server
  port: 8080
  base_path: /api
  webui:
    driver: gradio
    port: 8081

workflow:
  title:
  description:
  input: ${input}
  output: 
    embedding: ${output as json}

component:
  type: model
  task: face-embedding
  max_concurrent_count: 1
  family: insightface
  model: ./models/antelopev2
  action:
    image: ${input.face_image as image}
