controller:
  type: http-server
  port: 8080
  base_path: /api
  webui:
    driver: gradio
    port: 8081

workflow:
  title: Generate Text with LoRA Adapters
  description: Generate text using a base model enhanced with multiple LoRA adapters for style and domain adaptation.
  input: ${input}
  output:
    generated: ${output}

component:
  type: model
  task: text-generation
  model:
    provider: huggingface
    repository: meta-llama/Llama-2-7b-hf
    token: ${env.HUGGINGFACE_TOKEN}
  peft_adapters:
    - type: lora
      name: alpaca
      model: tloen/alpaca-lora-7b
      weight: 0.7
    - type: lora
      name: assistant
      model: plncmm/guanaco-lora-7b
      weight: 0.8
      device: cuda:0
  text: ${input.prompt as text}

  params:
    max_output_length: 2048
    temperature: 0.7
    top_p: 0.9
